@authUrl = https://api-campaign-us-2.goacoustic.com
@transactUrl = http://transact-campaign-us-2.goacoustic.com

@clientId = 8b48b50b-1362-4125-b364-1ab43eab9003
@clientSecret = 6b6e78e4-754c-420d-a267-3fb003de7972
@refreshToken = r07BrA1sVEphnQkBFZTJXyEgyrT3z0B0RQErcIns5X_gS1


### Generate Access Token
# @name auth
POST {{authUrl}}/oauth/token
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token
&client_id={{clientId}}
&client_secret={{clientSecret}}
&refresh_token={{refreshToken}}


### Send Transactional Mail
POST {{transactUrl}}/XTMail
Content-Type: text/xml
Authorization: Bearer {{auth.response.body.access_token}}

<XTMAILING>
    <CAMPAIGN_ID>25430036</CAMPAIGN_ID>
    <TRANSACTION_ID>opcional</TRANSACTION_ID>
    <SHOW_ALL_SEND_DETAIL>true</SHOW_ALL_SEND_DETAIL>
    <SEND_AS_BATCH>false</SEND_AS_BATCH>
    <NO_RETRY_ON_FAILURE>false</NO_RETRY_ON_FAILURE>

    <SAVE_COLUMNS>
        <COLUMN_NAME>variable_1</COLUMN_NAME>
        <COLUMN_NAME>variable_2</COLUMN_NAME>
        <COLUMN_NAME>variable_3</COLUMN_NAME>
        <COLUMN_NAME>variable_4</COLUMN_NAME>
        <COLUMN_NAME>variable_5</COLUMN_NAME>
    </SAVE_COLUMNS>

    <RECIPIENT>
        <EMAIL>jorellana@celmedia.cl</EMAIL>
        <BODY_TYPE>HTML</BODY_TYPE>

        <PERSONALIZATION>
            <TAG_NAME>variable_1</TAG_NAME>
            <VALUE>Variable 1</VALUE>
        </PERSONALIZATION>

        <PERSONALIZATION>
            <TAG_NAME>subject</TAG_NAME>
            <VALUE>Test</VALUE>
        </PERSONALIZATION>

        <PERSONALIZATION>
            <TAG_NAME>variable_2</TAG_NAME>
            <VALUE>API creada para BCI Normaliza</VALUE>
        </PERSONALIZATION>

        <PERSONALIZATION>
            <TAG_NAME>variable_3</TAG_NAME>
            <VALUE>Prueba de CELMEDIA...</VALUE>
        </PERSONALIZATION>

        <PERSONALIZATION>
            <TAG_NAME>variable_4</TAG_NAME>
            <VALUE>Gracias por comprar a través de la APP...</VALUE>
        </PERSONALIZATION>

        <PERSONALIZATION>
            <TAG_NAME>variable_5</TAG_NAME>
            <VALUE>Esta es la 5ta variable de su transacción</VALUE>
        </PERSONALIZATION>

        <ATTACHMENT>
            <NAME>Prueba_1.pdf</NAME>
            <MIME_TYPE>text/plain</MIME_TYPE>
            <DATA>JVBERi0xLjMKJcTl8uXrp/Og0MTGCjQgMCBvYmoKPDwgL0xlbmd0aCA1IDAgUiAvRmlsdGVyIC9GbGF0ZURl</DATA>
        </ATTACHMENT>

    </RECIPIENT>
</XTMAILING>
