<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<!-- Definition of the artifact -->
	<groupId>com.santander.cpe.nxhbsc</groupId>
	<artifactId>cpe-nxhbsc-bedatacomangment</artifactId>
	<version>1.0.2-SNAPSHOT</version>
	<packaging>jar</packaging>
	<!-- Information about the application -->
	<name>cpe-nxhbsc-bedatacomangment</name>
	<description>Microservice para la gestion de consentimiento de datos.</description>
	<!-- Use starter parent -->
	<parent>
		<groupId>com.santander.framework.springboot</groupId>
		<artifactId>santander-spring-boot-starter-parent</artifactId>
		<version>1.5.1</version>
	</parent>

	<!-- Java compile version -->
	<properties>
		<java.version>17</java.version>
		<org.mapstruct.version>1.6.3</org.mapstruct.version>
	</properties>


	<dependencies>

		<!-- Netty -->
		<dependency>
			<groupId>io.netty</groupId>
			<artifactId>netty-codec</artifactId>
			<version>4.1.133.Final</version>
		</dependency>

		<dependency>
			<groupId>io.netty</groupId>
			<artifactId>netty-codec-dns</artifactId>
			<version>4.2.13.Final</version>
		</dependency>

		<dependency>
			<groupId>io.netty</groupId>
			<artifactId>netty-codec-http</artifactId>
			<version>4.2.13.Final</version>
		</dependency>

		<dependency>
			<groupId>io.netty</groupId>
			<artifactId>netty-codec-http2</artifactId>
			<version>4.2.13.Final</version>
		</dependency>

		<dependency>
			<groupId>io.netty</groupId>
			<artifactId>netty-transport-native-epoll</artifactId>
			<version>4.2.13.Final</version>
		</dependency>

		<!-- Spring Boot -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot</artifactId>
			<version>3.5.14</version>
		</dependency>

		<dependency>
		    <groupId>org.apache.tomcat.embed</groupId>
		    <artifactId>tomcat-embed-core</artifactId>
		    <version>10.1.54</version>
		    <scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.mapstruct</groupId>
			<artifactId>mapstruct</artifactId>
			<version>${org.mapstruct.version}</version>
		</dependency>
	    <!-- Spring Boot Actuator dependency -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<!-- Servlet WebApp starter	-->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<!-- OpenAPI dependency -->
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
		</dependency>
		<!-- Santander libraries -->
		<!-- Core dependency -->
		<dependency>
			<groupId>com.santander.framework.springboot</groupId>
			<artifactId>santander-spring-boot-starter-core</artifactId>
		</dependency>       
		<!-- Logging dependency -->
		<dependency>
			<groupId>com.santander.framework.springboot</groupId>
			<artifactId>santander-spring-boot-starter-logging-basic</artifactId>
		</dependency>
		<!-- Cache dependency -->
		<dependency>
			<groupId>com.santander.framework.springboot</groupId>
			<artifactId>santander-spring-boot-starter-cache-caffeine</artifactId>
		</dependency>
		<!-- Authentication dependency -->
		<dependency>
			<groupId>com.santander.framework.springboot</groupId>
			<artifactId>santander-spring-boot-starter-authentication</artifactId>
		</dependency>
		<!-- Omnichannel dependency -->
		<dependency>
			<groupId>com.santander.framework.springboot</groupId>
			<artifactId>santander-spring-boot-starter-omnichannel</artifactId>
		</dependency>
		<!-- End Santander libraries -->
		<!--    Provided dependencies    -->
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<scope>provided</scope>
		</dependency>
		<!-- Test Dependencies -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<!-- Junit 5 Dependencies -->
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.platform</groupId>
			<artifactId>junit-platform-launcher</artifactId>
			<scope>test</scope>
		</dependency>
		<!-- Enables any legacy JUnit 3 and JUnit 4 tests you may have. Not needed for JUnit 5 tests. -->
		<dependency>
			<groupId>org.junit.vintage</groupId>
			<artifactId>junit-vintage-engine</artifactId>
			<scope>test</scope>
		</dependency>
		<!-- Spring security dependency for testing -->
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
	</dependencies>

	<build>
		<!-- Build plugins -->
		<plugins>
			<!-- Spring Boot Maven Plugin -->
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<!-- Maven Plugin for the encoding -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-resources-plugin</artifactId>
				<configuration>
					<encoding>${project.build.sourceEncoding}</encoding>
					<propertiesEncoding>ISO-8859-1</propertiesEncoding>
				</configuration>
			</plugin>
			<!-- Jacoco Maven Plugin for coverage -->
			<plugin>
				<groupId>org.jacoco</groupId>
				<artifactId>jacoco-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>default-prepare-agent</id>
						<goals>
							<goal>prepare-agent</goal>
						</goals>
					</execution>
					<execution>
						<id>default-report</id>
						<goals>
							<goal>report</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<!-- openapi plugin -->
			<plugin>
				<groupId>org.openapitools</groupId>
				<artifactId>openapi-generator-maven-plugin</artifactId>
				<executions>
					<execution>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<!-- specify the OpenAPI yaml -->
							<inputSpec>${project.basedir}/src/main/resources/openapi.yaml</inputSpec>

							<!-- target to generate java server code -->
							<generatorName>spring</generatorName>

							<!-- temporal to allow use test slice annotations as @DataJpaTest -->
							<templateDirectory>${project.basedir}/src/main/resources/openapi-templates</templateDirectory>

							<!-- hint: if you want to generate java client code
                                 you can use the following generator: <generatorName>java</generatorName> -->
							<apiPackage>com.santander.cpe.nxhbsc.cpenxhbscbedatacomangment.infrastructure.adapters.input.rest</apiPackage>
							<modelPackage>com.santander.cpe.nxhbsc.cpenxhbscbedatacomangment.infrastructure.adapters.input.rest.data</modelPackage>
							<invokerPackage>com.santander.cpe.nxhbsc.cpenxhbscbedatacomangment</invokerPackage>

							<!-- pass any necessary config options -->
							<configOptions>
								<documentationProvider>springdoc</documentationProvider>
								<serializableModel>true</serializableModel>
								<snapshotVersion>true</snapshotVersion>
								<implicitHeaders>true</implicitHeaders>
								<openApiNullable>false</openApiNullable>
								<delegatePattern>true</delegatePattern>
								<useSpringBoot3>true</useSpringBoot3>
								<configPackage>com.santander.cpe.nxhbsc.cpenxhbscbedatacomangment.infrastructure.config</configPackage>
							</configOptions>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.11.0</version>
				<configuration>
					<source>17</source>
					<target>17</target>
					<annotationProcessorPaths>
						<path>
							<groupId>org.mapstruct</groupId>
							<artifactId>mapstruct-processor</artifactId>
							<version>${org.mapstruct.version}</version>
						</path>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
							<version>${lombok.version}</version>
						</path>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok-mapstruct-binding</artifactId>
							<version>0.2.0</version>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>
		</plugins>
		<!-- End build Plugins -->
		<resources>
			<resource>
				<directory>${project.basedir}/src/main/resources</directory>
				<filtering>true</filtering>
				<includes>
					<include>**/*.properties</include>
					<include>**/*.yml</include>
					<include>**/*.yaml</include>
					<include>**/banner.txt</include>
					<include>**/santanderchannels.json</include>
				</includes>
			</resource>
		</resources>
	</build>
</project>
